server:
  port: ${PORT}

spring:
  cloud.gateway.server.webflux:
    routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/api/users/**
        filters:
          - StripPrefix=1

      - id: event-service
        uri: lb://EVENT-SERVICE
        predicates:
          - Path=/api/events/**
        filters:
          - StripPrefix=1
