server:
  port: ${PORT}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}   # or kafka:9092 if using docker-compose network
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest      # earliest = read from beginning if no offset
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all                        # strongest delivery guarantee
    listener:
      ack-mode: record
