server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RemoveRequestHeader=Authorization
            - AddResponseHeader=X-APP-NAME, EVENT-BOOKING-APP
            - AddResponseHeader=X-API-VERSION, API-V1
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
          routes:
            - id: user_service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2

            - id: event_service
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/api/events/**
              filters:
                - StripPrefix=2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka