server:
  port: 8020

spring:
  application:
    name: event-service
  data:
    mongodb:
      uri: mongodb://saurabh:saurabh123@localhost:6010/event_db?authSource=admin

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka